version: '3'
services:
  node:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./:/app
    restart: always
    ports:
      - "3000:3000"
  livego:
    image: gwuhaolin/livego
    tty: true
    restart: always
    ports:
      - "0.0.0.0:1935:1935"
      - "0.0.0.0:7001:7001"
      - "0.0.0.0:7002:7002"
      - "0.0.0.0:8090:8090"
